#!/bin/bash


if [ -e pythonversion ]
then
	pythonversion=`cat pythonversion`
else
	pythonversion=python3.6
fi


checkPID() {
	PID=`cat $1`

	if [ "$PID" == "-1" ]
		then
		running="-1"
	elif ps -p $PID > /dev/null
		then
		running="$PID"
	else 
		echo "-1" > $1
		running="-1"
	fi
	echo $running
}


if [ "$1" == "status" ]
	then	
	serverPID=`checkPID serverPID`
	if [ $serverPID == "-1" ]
	then
		echo "Isabelle server: down"
	else	
		echo "Isabelle server: up (PID=$serverPID)"
	fi

	pollerPID=`checkPID pollerPID`
	if [ $pollerPID == "-1" ]
	 then
		echo "Poller: down"
	else	
		echo "Poller: up (PID=$pollerPID)"
	fi 

elif [ "$1" == "stop" ]
then
	echo "A) stop Poller"
	./stoppoller.sh #TODO: stop gracefully, now the current grading task is just killed (but that's okay)!
	
	echo "B) stop Isabelle server"
	./stopserver.sh #TODO: stop gracefully, e.g. by sending shutdown message

elif [ "$1" == "start" ]
then
	./startserver.sh

	echo "C) starting poller now"

	echo "ready" > poller.watch

	sudo PYTHONPATH=.. $pythonversion poller_isa.py &
	pollerPID=$!
	echo "started a poller (PID=$pollerPID)"	
	echo $pollerPID > pollerPID

elif [ "$1" == "initwatchdog" ]
then
	echo $PWD > ~/.IsabellePoller
	

elif [ "$1" == "prepare" ]
then
	sudo ./prepareserver.sh

else 
	echo "Unknown command! usage: status|start|stop|prepare"
fi
