#!/bin/sh

# Set ACL2 to the first argument, if supplied.

if [ $# -ne 0 ] ; then \
    export ACL2="$1";\
fi

if [ "$ACL2" = "" ] ; then \
    echo "ERROR: Need to define ACL2 to point to your saved_acl2 executable.";\
    exit 1;
fi

export ACL2_DIR=`dirname $ACL2`

ACL2="$HOME/$ACL2"
ACL2_DIR="$HOME/$ACL2_DIR"

# echo $ACL2
 
cd /var/lib/acl2-grader/

# Remove all files generated by ACL2 (presumably from a previous check attempt).
"$ACL2_DIR"/books/build/clean.pl --acl2 "$ACL2"

# Certify the book check.lisp (and all necessary supporting books).
# It might be nice to support a -j option here.
"$ACL2_DIR"/books/build/cert.pl --acl2 "$ACL2" Check.lisp

# echo "$ACL2_DIR/books/build/cert.pl --acl2 $ACL2 /var/lib/acl2-grader/Check.lisp"

# Check that certificate file was generated.
if [ -f Check.cert ] ; then \
    echo "SUCCESS" ;\
    exit 0 ;\
else
    echo "FAILURE; see files *.cert.out" ;\ 
    exit 1 ;\
fi
